#!/bin/bash

set -e

BOSH_DATA_DIRECTORY=${BOSH_DATA_DIRECTORY:-/var/vcap/store}

cd $BOSH_DATA_DIRECTORY
echo "==== Begin creating tarball ===="
tar czf sonatype-work.tgz sonatype-work
echo "==== End creating tarball ===="
mv sonatype-work.tgz $BBR_ARTIFACT_DIRECTORY