#!/bin/bash

set -e

BOSH_DATA_DIRECTORY=${BOSH_DATA_DIRECTORY:-/var/vcap/store}
BACKUP_DIRECTORY="$BBR_ARTIFACT_DIRECTORY"
BLOBS_DIRECTORY="$BOSH_DATA_DIRECTORY"

echo "Start Restoring"
cd ${BOSH_DATA_DIRECTORY}
rm -f sonatype-work.tgz
mv ${BACKUP_DIRECTORY}/sonatype-work.tgz ./
tar xzvf sonatype-work.tgz
chown -R vcap:vcap ${BLOBS_DIRECTORY}