#!/bin/bash

set -e

BOSH_DATA_DIRECTORY=${BOSH_DATA_DIRECTORY:-/var/vcap/store}
BACKUP_DIRECTORY="$BBR_ARTIFACT_DIRECTORY"
BLOBS_DIRECTORY="$BOSH_DATA_DIRECTORY"
PID=`cat /var/vcap/sys/run/nexus/pid`

/var/vcap/bosh/bin/monit stop nexus

while [ -e /proc/$PID ];do
  echo "Waiting until process($PID) stops"
  sleep 1
done

cd ${BOSH_DATA_DIRECTORY}
rm -rf sonatype-work*
mv ${BACKUP_DIRECTORY}/sonatype-work.tgz ./
echo "==== Begin extracting tarball ===="
tar xzf sonatype-work.tgz
echo "==== End extracting tarball ===="
chown -R vcap:vcap ${BLOBS_DIRECTORY}
/var/vcap/bosh/bin/monit start nexus
rm -f sonatype-work.tgz