#!/bin/bash

set -e

BOSH_DATA_DIRECTORY=${BOSH_DATA_DIRECTORY:-/var/vcap/store}
BACKUP_DIRECTORY="$BBR_ARTIFACT_DIRECTORY"
BLOBS_DIRECTORY="$BOSH_DATA_DIRECTORY"

/var/vcap/bosh/bin/monit stop nexus
cd ${BOSH_DATA_DIRECTORY}
rm -rf sonatype-work*
mv ${BACKUP_DIRECTORY}/sonatype-work.tgz ./
echo "==== Begin creating tarball ===="
tar xzf sonatype-work.tgz
echo "==== End creating tarball ===="
chown -R vcap:vcap ${BLOBS_DIRECTORY}
/var/vcap/bosh/bin/monit start nexus
rm -f sonatype-work.tgz